import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads } from "react-icons/fa6";

// Tech stack icons
import { 
  SiPython, 
  SiJavascript, 
  SiTypescript, 
  SiReact, 
  SiNextdotjs, 
  SiNodedotjs, 
  SiMongodb, 
  SiPostgresql, 
  SiMysql, 
  SiDocker, 
  SiGit, 
  SiGithub, 
  SiTailwindcss, 
  SiHtml5, 
  SiCss3, 
  SiDjango, 
  SiFlask, 
  SiSpringboot,
  SiTensorflow,
  SiPytorch,
  SiPandas,
  SiNumpy,
  SiScikitlearn,
  SiJupyter,
  SiVsco,
  SiIntellijidea,
  SiPycharm,
  SiFigma,
  SiPostman,
  SiVercel,
  SiNetlify,
  SiAew,
  SiGooglecloud,
  SiFirebase
} from "react-icons/si";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  // Tech stack icons
  python: SiPython,
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  nextjs: SiNextdotjs,
  nodejs: SiNodedotjs,
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  docker: SiDocker,
  git: SiGit,
  tailwindcss: SiTailwindcss,
  html5: SiHtml5,
  css3: SiCss3,
  django: SiDjango,
  flask: SiFlask,
  springboot: SiSpringboot,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  pandas: SiPandas,
  numpy: SiNumpy,
  scikitlearn: SiScikitlearn,
  jupyter: SiJupyter,
  vscode: SiVsco,
  intellijidea: SiIntellijidea,
  pycharm: SiPycharm,
  figma: SiFigma,
  postman: SiPostman,
  vercel: SiVercel,
  netlify: SiNetlify,
  aws: SiAew,
  googlecloud: SiGooglecloud,
  firebase: SiFirebase
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;